<?php

$labels['setvacation'] = "Out of Office Autoresponder";
$labels['vacenabled'] = "Enable Autoresponder?";
$labels['vacsubject'] = "Email subject";
$labels['vacmessage'] = "Email message";
$labels['vacforward'] = "Forward to other address";
$labels['vacstarttime'] = "Time to turn on autoresponder";
$labels['vacendtime'] = "Time to turn off autoresponder";
$labels['vacstartdate'] = "Date to turn on autoresponder";
$labels['vacenddate'] = "Date to turn off autoresponder";
$labels['vacdateinstructions'] = "If the start/end dates are left blank, the autoresponder will be enabled indefinitely";
